title: Bravotty
url: "https://bravotty.github.io/"

markdown: kramdown
# ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/bravotty"
footer_text: "Page design by Ankit Sultana! Because im a rookie!"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Contact"
   link: "contact"

 - email: "E-mail"
   link : "bravotty@protonmail.com"
